# Generated by Django 4.2 on 2024-01-01 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todomodel',
            name='titla',
        ),
    ]
